version: '2'

services:
  db:
    build: dockerfiles/postgres/
  web:
    build: dockerfiles/django/
    expose:
      - "8000"
    depends_on:
      - db
    volumes:
      - ./annotable:/annotable
    command: bash -c "cd agdss && cp -r /annotable/small-tomatoes/ webclient/static/ && rm -rf static-root && python3 manage.py collectstatic --settings=agdss.settings.common && python3 manage.py runserver 0.0.0.0:8000 --settings=agdss.settings.common && cd /code/agdss-1/static-root/small-tomatoes/ && bash addImages.sh tomato"


networks:  
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/16
          gateway: 172.30.0.1
