networks:
  default:
    ipam:
      config:
      - gateway: 172.30.0.1
        subnet: 172.30.0.0/16
      driver: default
services:
  db:
    build: dockerfiles/postgres/
    devices:
    - /dev/nvidia0
    - /dev/nvidia1
    - /dev/nvidiactl
    - /dev/nvidia-uvm
    - /dev/nvidia-uvm-tools
    volumes:
    - nvidia_driver_384.111:/usr/local/nvidia:ro
  web:
    build: dockerfiles/django/
    command: bash -c "cd agdss && cp -r /annotable/small-tomatoes/ webclient/static/
      && rm -rf static-root && python3 manage.py collectstatic --settings=agdss.settings.common
      && python3 manage.py runserver 0.0.0.0:8000 --settings=agdss.settings.common
      && cd /code/agdss-1/static-root/small-tomatoes/ && bash addImages.sh tomato"
    depends_on:
    - db
    devices:
    - /dev/nvidia0
    - /dev/nvidia1
    - /dev/nvidiactl
    - /dev/nvidia-uvm
    - /dev/nvidia-uvm-tools
    expose:
    - '8000'
    volumes:
    - ./annotable:/annotable
    - nvidia_driver_384.111:/usr/local/nvidia:ro
version: '2'
volumes:
  nvidia_driver_384.111:
    external: true
